# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_gvemgrm <- function(y, R, old_A, old_B, old_sig, old_ksi1, old_ksi2, Mod, is_sigmaknown, max_iter = 100L, tol_n2vlb = 1e-4, tol_para = 1e-3, stop_cri = 2L, is_calcu_n2vlb = 0L) {
    .Call(`_GVEMGRM_rcpp_gvemgrm`, y, R, old_A, old_B, old_sig, old_ksi1, old_ksi2, Mod, is_sigmaknown, max_iter, tol_n2vlb, tol_para, stop_cri, is_calcu_n2vlb)
}

rcpp_iwgvemgrm <- function(y, R, old_A, old_B, old_sig, mu_n, sigma_n, Mod, is_sigmaknown, S = 10L, M = 10L, beta1 = 0.9, beta2 = 0.999, eta_A = 0.05, eta_gam = 0.01, eta_sig = 0.005, eps = 0.001, max_iter = 100L, tol_para = 1e-4) {
    .Call(`_GVEMGRM_rcpp_iwgvemgrm`, y, R, old_A, old_B, old_sig, mu_n, sigma_n, Mod, is_sigmaknown, S, M, beta1, beta2, eta_A, eta_gam, eta_sig, eps, max_iter, tol_para)
}

